<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_645114dbeea6e',
		'title' => 'CivicPlus Settings',
		'fields' => array(
			array(
				'key' => 'field_645119e8c51ff',
				'label' => 'General',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_645114dc4ace8',
				'label' => 'General',
				'name' => 'general',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_64511509841b6',
						'label' => 'Logo',
						'name' => 'logo',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'uploader' => '',
						'return_format' => 'array',
						'acfe_thumbnail' => 0,
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array(
						'key' => 'field_645115ed77173',
						'label' => 'Top Header Links',
						'name' => 'header_links',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'block',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Link',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_645115ed77174',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => '',
								'parent_repeater' => 'field_645115ed77173',
							),
						),
					),
					array(
						'key' => 'field_64511521e71c6',
						'label' => 'Header Buttons',
						'name' => 'header_buttons',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'table',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Button',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_64511536e71c7',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => 'array',
								'parent_repeater' => 'field_64511521e71c6',
							),
							array(
								'key' => 'field_64511541e71c8',
								'label' => 'Type',
								'name' => 'type',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'choices' => array(
									'btn-red secondary' => 'Simple Text',
									'btn-red' => 'Red',
								),
								'default_value' => false,
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'allow_custom' => 0,
								'search_placeholder' => '',
								'parent_repeater' => 'field_64511521e71c6',
							),
						),
					),
					array(
						'key' => 'field_6451156c0053f',
						'label' => 'Location',
						'name' => 'location',
						'aria-label' => '',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'acfe_textarea_code' => 0,
						'maxlength' => '',
						'rows' => 3,
						'placeholder' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_6451157700540',
						'label' => 'Phone',
						'name' => 'phone',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_6451158200541',
						'label' => 'Awards',
						'name' => 'awards',
						'aria-label' => '',
						'type' => 'gallery',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'return_format' => 'id',
						'library' => 'all',
						'min' => '',
						'max' => '',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'insert' => 'append',
						'preview_size' => 'medium',
					),
					array(
						'key' => 'field_6451159bb299e',
						'label' => 'Copy',
						'name' => 'copy',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '© 2023 CivicPlus',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_645115acb299f',
						'label' => 'Footer Links',
						'name' => 'footer_links',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'table',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Link',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_645115bab29a0',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => 'array',
								'parent_repeater' => 'field_645115acb299f',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_64511a09fb5ad',
				'label' => 'Header Menu',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64511a1dfb5ae',
				'label' => 'Header Menu',
				'name' => 'header_menu',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'acfe_repeater_stylised_button' => 0,
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_64511c3efb5af',
						'label' => 'Is It Link?',
						'name' => 'is_it_link',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'parent_repeater' => 'field_64511a1dfb5ae',
					),
					array(
						'key' => 'field_64511c52fb5b0',
						'label' => 'Link',
						'name' => 'link',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_64511c3efb5af',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'return_format' => 'array',
						'parent_repeater' => 'field_64511a1dfb5ae',
					),
					array(
						'key' => 'field_64511c6dfb5b1',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_64511c3efb5af',
									'operator' => '!=',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_64511a1dfb5ae',
					),
					array(
						'key' => 'field_64511c84fb5b2',
						'label' => 'Submenu',
						'name' => 'submenu',
						'aria-label' => '',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_64511c3efb5af',
									'operator' => '!=',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_flexible_advanced' => 1,
						'acfe_flexible_stylised_button' => 0,
						'acfe_flexible_hide_empty_message' => 0,
						'acfe_flexible_empty_message' => 'Add Submenu',
						'acfe_flexible_layouts_templates' => 0,
						'acfe_flexible_layouts_placeholder' => 0,
						'acfe_flexible_layouts_thumbnails' => 1,
						'acfe_flexible_layouts_settings' => 0,
						'acfe_flexible_async' => array(
						),
						'acfe_flexible_add_actions' => array(
							0 => 'title',
							1 => 'toggle',
							2 => 'copy',
						),
						'acfe_flexible_remove_button' => array(
						),
						'acfe_flexible_layouts_state' => 'user',
						'acfe_flexible_modal_edit' => array(
							'acfe_flexible_modal_edit_enabled' => '0',
							'acfe_flexible_modal_edit_size' => 'large',
						),
						'acfe_flexible_modal' => array(
							'acfe_flexible_modal_enabled' => '1',
							'acfe_flexible_modal_title' => '',
							'acfe_flexible_modal_size' => 'full',
							'acfe_flexible_modal_col' => '4',
							'acfe_flexible_modal_categories' => '0',
						),
						'layouts' => array(
							'layout_64511c9156345' => array(
								'key' => 'layout_64511c9156345',
								'name' => 'type_a',
								'label' => 'Type A',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_64511f53a8910',
										'label' => 'Tabs',
										'name' => 'tabs',
										'aria-label' => '',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'acfe_repeater_stylised_button' => 0,
										'layout' => 'block',
										'min' => 0,
										'max' => 0,
										'collapsed' => 'field_64511fbea8911',
										'button_label' => 'Add Tab',
										'rows_per_page' => 20,
										'sub_fields' => array(
											array(
												'key' => 'field_64511fbea8911',
												'label' => 'Title',
												'name' => 'title',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'parent_repeater' => 'field_64511f53a8910',
											),
											array(
												'key' => 'field_64511fc4a8912',
												'label' => 'Description',
												'name' => 'description',
												'aria-label' => '',
												'type' => 'textarea',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'acfe_textarea_code' => 0,
												'maxlength' => '',
												'rows' => '',
												'placeholder' => '',
												'new_lines' => '',
												'parent_repeater' => 'field_64511f53a8910',
											),
											array(
												'key' => 'field_64512a50355af',
												'label' => 'Columns',
												'name' => 'columns',
												'aria-label' => '',
												'type' => 'repeater',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'acfe_repeater_stylised_button' => 0,
												'layout' => 'block',
												'pagination' => 0,
												'min' => 0,
												'max' => 0,
												'collapsed' => 'field_64512a6d355b0',
												'button_label' => 'Add Column',
												'rows_per_page' => 20,
												'parent_repeater' => 'field_64511f53a8910',
												'sub_fields' => array(
													array(
														'key' => 'field_64512a6d355b0',
														'label' => 'Title',
														'name' => 'title',
														'aria-label' => '',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => '',
														'maxlength' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'parent_repeater' => 'field_64512a50355af',
													),
													array(
														'key' => 'field_64512a7d355b1',
														'label' => 'Buttons',
														'name' => 'buttons',
														'aria-label' => '',
														'type' => 'repeater',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'acfe_repeater_stylised_button' => 0,
														'layout' => 'block',
														'pagination' => 0,
														'min' => 0,
														'max' => 0,
														'collapsed' => 'field_64512f41355b3',
														'button_label' => 'Add Button',
														'rows_per_page' => 20,
														'parent_repeater' => 'field_64512a50355af',
														'sub_fields' => array(
															array(
																'key' => 'field_64512de5355b2',
																'label' => 'Image',
																'name' => 'image',
																'aria-label' => '',
																'type' => 'image',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'acfe_save_meta' => 0,
																'uploader' => '',
																'return_format' => 'id',
																'acfe_thumbnail' => 0,
																'min_width' => '',
																'min_height' => '',
																'min_size' => '',
																'max_width' => '',
																'max_height' => '',
																'max_size' => '',
																'mime_types' => '',
																'preview_size' => 'medium',
																'library' => 'all',
																'parent_repeater' => 'field_64512a7d355b1',
															),
															array(
																'key' => 'field_64512f41355b3',
																'label' => 'Link',
																'name' => 'link',
																'aria-label' => '',
																'type' => 'link',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'acfe_save_meta' => 0,
																'return_format' => 'array',
																'parent_repeater' => 'field_64512a7d355b1',
															),
															array(
																'key' => 'field_64512f4e355b4',
																'label' => 'Description',
																'name' => 'description',
																'aria-label' => '',
																'type' => 'text',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'acfe_save_meta' => 0,
																'default_value' => '',
																'maxlength' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
																'parent_repeater' => 'field_64512a7d355b1',
															),
														),
													),
												),
											),
										),
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_thumbnail' => '314',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
							'layout_645151b33d2f1' => array(
								'key' => 'layout_645151b33d2f1',
								'name' => 'type_b',
								'label' => 'Type B',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_645151c53d2f3',
										'label' => 'Tag',
										'name' => 'tag',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
									array(
										'key' => 'field_645151d23d2f4',
										'label' => 'Buttons',
										'name' => 'buttons',
										'aria-label' => '',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'acfe_repeater_stylised_button' => 0,
										'layout' => 'block',
										'min' => 0,
										'max' => 0,
										'collapsed' => 'field_6451520c3d2f6',
										'button_label' => 'Add Button',
										'rows_per_page' => 20,
										'sub_fields' => array(
											array(
												'key' => 'field_645151ea3d2f5',
												'label' => 'Image',
												'name' => 'image',
												'aria-label' => '',
												'type' => 'image',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'uploader' => '',
												'return_format' => 'id',
												'acfe_thumbnail' => 0,
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
												'preview_size' => 'medium',
												'library' => 'all',
												'parent_repeater' => 'field_645151d23d2f4',
											),
											array(
												'key' => 'field_6451520c3d2f6',
												'label' => 'Link',
												'name' => 'link',
												'aria-label' => '',
												'type' => 'link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'return_format' => 'array',
												'parent_repeater' => 'field_645151d23d2f4',
											),
											array(
												'key' => 'field_645152173d2f7',
												'label' => 'Description',
												'name' => 'description',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'parent_repeater' => 'field_645151d23d2f4',
											),
										),
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_thumbnail' => '329',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
							'layout_6451527c23ad9' => array(
								'key' => 'layout_6451527c23ad9',
								'name' => 'type_c',
								'label' => 'Type C',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_645152a523adb',
										'label' => 'Title',
										'name' => 'title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
									array(
										'key' => 'field_645152ad23adc',
										'label' => 'Buttons',
										'name' => 'buttons',
										'aria-label' => '',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'acfe_repeater_stylised_button' => 0,
										'layout' => 'block',
										'min' => 0,
										'max' => 0,
										'collapsed' => 'field_645152cc23ade',
										'button_label' => 'Add Button',
										'rows_per_page' => 20,
										'sub_fields' => array(
											array(
												'key' => 'field_645152c023add',
												'label' => 'Image',
												'name' => 'image',
												'aria-label' => '',
												'type' => 'image',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'uploader' => '',
												'return_format' => 'id',
												'acfe_thumbnail' => 0,
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
												'preview_size' => 'medium',
												'library' => 'all',
												'parent_repeater' => 'field_645152ad23adc',
											),
											array(
												'key' => 'field_645152cc23ade',
												'label' => 'Link',
												'name' => 'link',
												'aria-label' => '',
												'type' => 'link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'return_format' => 'array',
												'parent_repeater' => 'field_645152ad23adc',
											),
											array(
												'key' => 'field_645152d923adf',
												'label' => 'Description',
												'name' => 'description',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'parent_repeater' => 'field_645152ad23adc',
											),
										),
									),
									array(
										'key' => 'field_645152e823ae0',
										'label' => 'Post',
										'name' => 'post',
										'aria-label' => '',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'post_type' => '',
										'taxonomy' => '',
										'return_format' => 'id',
										'multiple' => 0,
										'save_custom' => 0,
										'save_post_status' => 'publish',
										'acfe_bidirectional' => array(
											'acfe_bidirectional_enabled' => '0',
										),
										'allow_null' => 0,
										'ui' => 1,
										'save_post_type' => '',
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_thumbnail' => '330',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
						),
						'min' => '',
						'max' => 1,
						'button_label' => 'Add Submenu',
						'acfe_flexible_layouts_previews' => false,
						'parent_repeater' => 'field_64511a1dfb5ae',
					),
				),
			),
			array(
				'key' => 'field_6451530e574a6',
				'label' => 'Footer Menu',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64515321574a7',
				'label' => 'Footer Menu',
				'name' => 'footer_menu',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'acfe_repeater_stylised_button' => 0,
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Column',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_64515388574a8',
						'label' => 'Buttons',
						'name' => 'buttons',
						'aria-label' => '',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_flexible_advanced' => 1,
						'acfe_flexible_stylised_button' => 0,
						'acfe_flexible_hide_empty_message' => 0,
						'acfe_flexible_empty_message' => '',
						'acfe_flexible_layouts_templates' => 0,
						'acfe_flexible_layouts_placeholder' => 0,
						'acfe_flexible_layouts_thumbnails' => 0,
						'acfe_flexible_layouts_settings' => 0,
						'acfe_flexible_async' => array(
						),
						'acfe_flexible_add_actions' => array(
							0 => 'title',
							1 => 'toggle',
							2 => 'copy',
						),
						'acfe_flexible_remove_button' => array(
						),
						'acfe_flexible_layouts_state' => 'user',
						'acfe_flexible_modal_edit' => array(
							'acfe_flexible_modal_edit_enabled' => '0',
							'acfe_flexible_modal_edit_size' => 'large',
						),
						'acfe_flexible_modal' => array(
							'acfe_flexible_modal_enabled' => '0',
							'acfe_flexible_modal_title' => false,
							'acfe_flexible_modal_size' => 'full',
							'acfe_flexible_modal_col' => '4',
							'acfe_flexible_modal_categories' => false,
						),
						'layouts' => array(
							'layout_6451539053d84' => array(
								'key' => 'layout_6451539053d84',
								'name' => 'title',
								'label' => 'Title',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_645153a4574a9',
										'label' => 'Title',
										'name' => 'title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
							'layout_645153b9574aa' => array(
								'key' => 'layout_645153b9574aa',
								'name' => 'simple_link',
								'label' => 'Simple Link',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_645153c7574ac',
										'label' => 'Link',
										'name' => 'link',
										'aria-label' => '',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'return_format' => 'array',
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
							'layout_645153d1574ad' => array(
								'key' => 'layout_645153d1574ad',
								'name' => 'bold_link',
								'label' => 'Bold Link',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_645153d8574af',
										'label' => 'Link',
										'name' => 'link',
										'aria-label' => '',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'return_format' => 'array',
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
							'layout_645153e6574b0' => array(
								'key' => 'layout_645153e6574b0',
								'name' => 'title_link',
								'label' => 'Title Link',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_64515455d5476',
										'label' => 'Link',
										'name' => 'link',
										'aria-label' => '',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'return_format' => 'array',
									),
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
							'layout_645153f1574b2' => array(
								'key' => 'layout_645153f1574b2',
								'name' => 'empty_space',
								'label' => 'Empty Space',
								'display' => 'block',
								'sub_fields' => array(
								),
								'min' => '',
								'max' => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings' => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category' => false,
							),
						),
						'min' => '',
						'max' => '',
						'button_label' => 'Add Button',
						'acfe_flexible_layouts_previews' => false,
						'parent_repeater' => 'field_64515321574a7',
					),
				),
			),
			array(
				'key' => 'field_646282b0c50f0',
				'label' => 'Archives',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_647a0a3bd4c29',
				'label' => 'Case Studies',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_647a0a48d4c2a',
				'label' => 'Case Studies',
				'name' => 'case_studies',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => '',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633e7aab0ef',
				'label' => 'Resources',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633e87ab0f0',
				'label' => 'Resources',
				'name' => 'resources',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_646282bfc50f1',
				'label' => 'Blog',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_646282e1c50f2',
				'label' => 'Blog',
				'name' => 'blog',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_6462835409c30',
				'label' => 'Brochure',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6462836709c31',
				'label' => 'Brochure',
				'name' => 'brochure',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_6462837c1eca2',
				'label' => 'White Paper',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_646283851eca3',
				'label' => 'White Paper',
				'name' => 'white_paper',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633a02bc7dc',
				'label' => 'Webinars',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633a0fbc7dd',
				'label' => 'Webinars',
				'name' => 'webinars',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633a42b398b',
				'label' => 'eBooks',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633a5cb398c',
				'label' => 'eBooks',
				'name' => 'ebooks',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633a86b118c',
				'label' => 'Fact Sheets',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633a90b118d',
				'label' => 'Fact Sheets',
				'name' => 'fact_sheets',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633ab4c20e2',
				'label' => 'Tool Kit',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633ac5c20e4',
				'label' => 'Tool Kit',
				'name' => 'tool_kit',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633e2afb1f8',
				'label' => 'Infographics',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633e36fb1f9',
				'label' => 'Infographics',
				'name' => 'infographics',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64633e4afb1fd',
				'label' => 'Videos',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64633e62c1a45',
				'label' => 'Video',
				'name' => 'video',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_646343786e299',
					1 => 'field_646343786e29a',
					2 => 'field_646343786e29b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_6464886aad0f2',
				'label' => 'Close',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 1,
			),
			array(
				'key' => 'field_64648878ad0f3',
				'label' => 'Resources Demo',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64648890ad0f4',
				'label' => 'Demo',
				'name' => 'demo',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
				'sub_fields' => array(
					array(
						'key' => 'field_6464a60e70b25',
						'label' => 'Is It Hidden?',
						'name' => 'is_it_hidden',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_646488b0ad0f7',
						'label' => 'Type',
						'name' => 'type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'choices' => array(
							'type_a' => 'Type A',
							'type_b' => 'Type B',
						),
						'default_value' => false,
						'return_format' => '',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'allow_custom' => 0,
						'search_placeholder' => '',
					),
					array(
						'key' => 'field_6464889ead0f5',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_646488a8ad0f6',
						'label' => 'Subtitle',
						'name' => 'subtitle',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_646488e9ad0f8',
						'label' => 'List',
						'name' => 'list',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_646488b0ad0f7',
									'operator' => '==',
									'value' => 'type_a',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'block',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Row',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_646488f9ad0f9',
								'label' => 'Image',
								'name' => 'image',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'uploader' => '',
								'return_format' => 'id',
								'acfe_thumbnail' => 0,
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'preview_size' => 'medium',
								'library' => 'all',
								'parent_repeater' => 'field_646488e9ad0f8',
							),
							array(
								'key' => 'field_64648909ad0fa',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_646488e9ad0f8',
							),
						),
					),
					array(
						'key' => 'field_6464892bad0fb',
						'label' => 'Buttons',
						'name' => 'buttons',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'table',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Row',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_64648941ad0fc',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => 'array',
								'parent_repeater' => 'field_6464892bad0fb',
							),
							array(
								'key' => 'field_64648951ad0fd',
								'label' => 'Type',
								'name' => 'type',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'choices' => array(
									'btn' => 'Default',
									'btn secondary' => 'Secondary',
								),
								'default_value' => false,
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'allow_custom' => 0,
								'search_placeholder' => '',
								'parent_repeater' => 'field_6464892bad0fb',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_64ac0d73acfa4',
				'label' => '404',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64ac0d8cacfa6',
				'label' => '404 Hero',
				'name' => '404_hero',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_645014f441a37',
				),
				'display' => 'seamless',
				'layout' => '',
				'prefix_label' => 0,
				'prefix_name' => 0,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_64ac1026ba020',
				'label' => '404 Content',
				'name' => '404_content',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'acfe_flexible_advanced' => 1,
				'acfe_flexible_stylised_button' => 0,
				'acfe_flexible_hide_empty_message' => 0,
				'acfe_flexible_empty_message' => 'Add Section',
				'acfe_flexible_layouts_templates' => 0,
				'acfe_flexible_layouts_placeholder' => 0,
				'acfe_flexible_layouts_thumbnails' => 1,
				'acfe_flexible_layouts_settings' => 0,
				'acfe_flexible_async' => array(
					0 => 'layout',
				),
				'acfe_flexible_add_actions' => array(
					0 => 'title',
					1 => 'toggle',
					2 => 'copy',
					3 => 'lock',
				),
				'acfe_flexible_remove_button' => array(
				),
				'acfe_flexible_layouts_state' => 'user',
				'acfe_flexible_modal_edit' => array(
					'acfe_flexible_modal_edit_enabled' => '0',
					'acfe_flexible_modal_edit_size' => 'large',
				),
				'acfe_flexible_modal' => array(
					'acfe_flexible_modal_enabled' => '1',
					'acfe_flexible_modal_title' => '',
					'acfe_flexible_modal_size' => 'full',
					'acfe_flexible_modal_col' => '2',
					'acfe_flexible_modal_categories' => '0',
				),
				'layouts' => array(
					'layout_64ac11c68476a' => array(
						'key' => 'layout_64ac11c68476a',
						'name' => 'cards',
						'label' => 'cards',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_64ac12468476c',
								'label' => 'Cards',
								'name' => 'cards',
								'aria-label' => '',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'clone' => array(
									0 => 'field_645024f1520f5',
									1 => 'field_645024f1520f6',
									2 => 'field_645024f1520f7',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
								'acfe_seamless_style' => 0,
								'acfe_clone_modal' => 0,
								'acfe_clone_modal_close' => 0,
								'acfe_clone_modal_button' => '',
								'acfe_clone_modal_size' => 'large',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_64ac10be4dd7d' => array(
						'key' => 'layout_64ac10be4dd7d',
						'name' => 'resources',
						'label' => 'Resources',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_64ac10c6ba022',
								'label' => 'Resources',
								'name' => 'resources',
								'aria-label' => '',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'clone' => array(
									0 => 'field_6450283ce2e37',
									1 => 'field_64502842e2e38',
									2 => 'field_6450286fe2e3a',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
								'acfe_seamless_style' => 0,
								'acfe_clone_modal' => 0,
								'acfe_clone_modal_close' => 0,
								'acfe_clone_modal_button' => '',
								'acfe_clone_modal_size' => 'large',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
				),
				'min' => '',
				'max' => '',
				'button_label' => 'Add Row',
				'acfe_flexible_layouts_previews' => false,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'civicplus-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	));

endif;