<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_646dbed1500f9',
		'title' => 'Template Services',
		'fields' => array(
			array(
				'key' => 'field_646dbed151738',
				'label' => 'Hero',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_646dbed15173e',
				'label' => 'Hero',
				'name' => 'hero',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_645014f441a37',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
			array(
				'key' => 'field_646dbed151741',
				'label' => 'Content',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_646dbed151744',
				'label' => 'Content',
				'name' => 'content',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'acfe_flexible_advanced' => 1,
				'acfe_flexible_stylised_button' => 0,
				'acfe_flexible_hide_empty_message' => 0,
				'acfe_flexible_empty_message' => 'Add Section',
				'acfe_flexible_layouts_templates' => 0,
				'acfe_flexible_layouts_placeholder' => 0,
				'acfe_flexible_layouts_thumbnails' => 1,
				'acfe_flexible_layouts_settings' => 0,
				'acfe_flexible_async' => array(
					0 => 'layout',
				),
				'acfe_flexible_add_actions' => array(
					0 => 'title',
					1 => 'toggle',
					2 => 'copy',
				),
				'acfe_flexible_remove_button' => array(
				),
				'acfe_flexible_layouts_state' => 'user',
				'acfe_flexible_modal_edit' => array(
					'acfe_flexible_modal_edit_enabled' => '0',
					'acfe_flexible_modal_edit_size' => 'large',
				),
				'acfe_flexible_modal' => array(
					'acfe_flexible_modal_enabled' => '1',
					'acfe_flexible_modal_title' => 'Add Section',
					'acfe_flexible_modal_size' => 'full',
					'acfe_flexible_modal_col' => '4',
					'acfe_flexible_modal_categories' => '0',
				),
				'layouts' => array(
					'layout_645026f69c9f4' => array(
						'key' => 'layout_645026f69c9f4',
						'name' => 'cards',
						'label' => 'Cards',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_646dc28618079',
								'label' => 'Image',
								'name' => 'image',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'uploader' => '',
								'return_format' => 'id',
								'acfe_thumbnail' => 0,
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array(
								'key' => 'field_646dbed153bf9',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '70',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_646dbed153c02',
								'label' => 'Content',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 1,
							),
							array(
								'key' => 'field_646dc2e12f6b1',
								'label' => 'List',
								'name' => 'list',
								'aria-label' => '',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'acfe_repeater_stylised_button' => 0,
								'layout' => 'block',
								'min' => 0,
								'max' => 0,
								'collapsed' => 'field_646dc36a2f6b2',
								'button_label' => 'Add Card',
								'rows_per_page' => 20,
								'sub_fields' => array(
									array(
										'key' => 'field_646dc36f2f6b3',
										'label' => 'Image',
										'name' => 'image',
										'aria-label' => '',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'uploader' => '',
										'return_format' => '',
										'acfe_thumbnail' => 0,
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
										'preview_size' => 'medium',
										'library' => 'all',
										'parent_repeater' => 'field_646dc2e12f6b1',
									),
									array(
										'key' => 'field_646dc36a2f6b2',
										'label' => 'Title',
										'name' => 'title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'parent_repeater' => 'field_646dc2e12f6b1',
									),
									array(
										'key' => 'field_646dc37d2f6b4',
										'label' => 'Description',
										'name' => 'description',
										'aria-label' => '',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 1,
										'parent_repeater' => 'field_646dc2e12f6b1',
									),
									array(
										'key' => 'field_646dc3992f6b5',
										'label' => 'Link',
										'name' => 'link',
										'aria-label' => '',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'return_format' => 'array',
										'parent_repeater' => 'field_646dc2e12f6b1',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_646dc2c62f6ad' => array(
						'key' => 'layout_646dc2c62f6ad',
						'name' => 'cards_and_feedback',
						'label' => 'Cards and Feedback',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_646dc2c62f6ae',
								'label' => 'Image',
								'name' => 'image',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'uploader' => '',
								'return_format' => 'id',
								'acfe_thumbnail' => 0,
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array(
								'key' => 'field_646dc2c62f6af',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '70',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_646dc2c62f6b0',
								'label' => 'Content',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 1,
							),
							array(
								'key' => 'field_646dc3beea6da',
								'label' => 'List',
								'name' => 'list',
								'aria-label' => '',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'acfe_repeater_stylised_button' => 0,
								'layout' => 'block',
								'min' => 0,
								'max' => 0,
								'collapsed' => 'field_646dc3beea6dc',
								'button_label' => 'Add Card',
								'rows_per_page' => 20,
								'sub_fields' => array(
									array(
										'key' => 'field_646dc3beea6db',
										'label' => 'Image',
										'name' => 'image',
										'aria-label' => '',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'uploader' => '',
										'return_format' => '',
										'library' => '',
										'acfe_thumbnail' => 0,
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
										'preview_size' => 'medium',
										'parent_repeater' => 'field_646dc3beea6da',
									),
									array(
										'key' => 'field_646dc3beea6dc',
										'label' => 'Title',
										'name' => 'title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'parent_repeater' => 'field_646dc3beea6da',
									),
									array(
										'key' => 'field_646dc3beea6dd',
										'label' => 'Description',
										'name' => 'description',
										'aria-label' => '',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 1,
										'parent_repeater' => 'field_646dc3beea6da',
									),
									array(
										'key' => 'field_646dc3beea6de',
										'label' => 'Link',
										'name' => 'link',
										'aria-label' => '',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'return_format' => '',
										'parent_repeater' => 'field_646dc3beea6da',
									),
								),
							),
							array(
								'key' => 'field_646dc3ddea6df',
								'label' => 'Feedback',
								'name' => 'feedback',
								'aria-label' => '',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'layout' => 'block',
								'acfe_seamless_style' => 1,
								'sub_fields' => array(
									array(
										'key' => 'field_646dc3f0ea6e0',
										'label' => 'Name',
										'name' => 'name',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
									array(
										'key' => 'field_646dc414ea6e2',
										'label' => 'Position',
										'name' => 'position',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
									array(
										'key' => 'field_646dc3f6ea6e1',
										'label' => 'Content',
										'name' => 'content',
										'aria-label' => '',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 1,
									),
								),
								'acfe_group_modal' => 0,
								'acfe_group_modal_close' => 0,
								'acfe_group_modal_button' => '',
								'acfe_group_modal_size' => 'large',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_646dc44de019a' => array(
						'key' => 'layout_646dc44de019a',
						'name' => 'cta',
						'label' => 'cta',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_646dc45be019c',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_646dc461e019d',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => 'array',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
				),
				'min' => '',
				'max' => '',
				'button_label' => 'Add Section',
				'acfe_flexible_layouts_previews' => false,
			),
			array(
				'key' => 'field_646dbed151747',
				'label' => 'Demo',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_646dbed15174a',
				'label' => 'Demo',
				'name' => 'demo',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_644fc17a8680b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-services.blade.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	));

endif;