<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_645012cc1a3aa',
		'title' => 'Template Home',
		'fields' => array(
			array(
				'key' => 'field_644becd19da86',
				'label' => 'Hero',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_644be8fcb5aed',
				'label' => 'Hero',
				'name' => 'hero',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'sub_fields' => array(
					array(
						'key' => 'field_644be952b5aef',
						'label' => 'Tag',
						'name' => 'tag',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_644be93eb5aee',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_644be95db5af0',
						'label' => 'Subtitle',
						'name' => 'subtitle',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_644be979b5af1',
						'label' => 'Link',
						'name' => 'link',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'return_format' => 'array',
					),
					array(
						'key' => 'field_644be9a5b5af2',
						'label' => 'Achievements',
						'name' => 'achievements',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'table',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Achievement',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_644be9c2b5af3',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_644be9a5b5af2',
							),
							array(
								'key' => 'field_644be9cbb5af4',
								'label' => 'Description',
								'name' => 'description',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_644be9a5b5af2',
							),
						),
					),
					array(
						'key' => 'field_6450fef1ac70f',
						'label' => 'Image',
						'name' => 'image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'uploader' => '',
						'return_format' => 'id',
						'acfe_thumbnail' => 0,
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
			),
			array(
				'key' => 'field_644becdf9da87',
				'label' => 'Announcement',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_644bea32b5af5',
				'label' => 'Announcement',
				'name' => 'announcement',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'layout' => 'block',
				'acfe_seamless_style' => 1,
				'sub_fields' => array(
					array(
						'key' => 'field_644bea54b5af6',
						'label' => 'Tag',
						'name' => 'tag',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_644bea6bb5af7',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_644bea71b5af8',
						'label' => 'Link',
						'name' => 'link',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 0,
						'return_format' => 'array',
					),
				),
				'acfe_group_modal' => 0,
				'acfe_group_modal_close' => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size' => 'large',
			),
			array(
				'key' => 'field_644beceb9da88',
				'label' => 'Content',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_644beacbb5af9',
				'label' => 'Content',
				'name' => 'content',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'acfe_flexible_advanced' => 1,
				'acfe_flexible_stylised_button' => 0,
				'acfe_flexible_hide_empty_message' => 0,
				'acfe_flexible_empty_message' => '',
				'acfe_flexible_layouts_templates' => 0,
				'acfe_flexible_layouts_placeholder' => 0,
				'acfe_flexible_layouts_thumbnails' => 1,
				'acfe_flexible_layouts_settings' => 0,
				'acfe_flexible_async' => array(
					0 => 'layout',
				),
				'acfe_flexible_add_actions' => array(
					0 => 'title',
					1 => 'toggle',
					2 => 'copy',
				),
				'acfe_flexible_remove_button' => array(
				),
				'acfe_flexible_layouts_state' => 'user',
				'acfe_flexible_modal_edit' => array(
					'acfe_flexible_modal_edit_enabled' => '0',
					'acfe_flexible_modal_edit_size' => 'large',
				),
				'acfe_flexible_modal' => array(
					'acfe_flexible_modal_enabled' => '1',
					'acfe_flexible_modal_title' => 'Add Section',
					'acfe_flexible_modal_size' => 'full',
					'acfe_flexible_modal_col' => '4',
					'acfe_flexible_modal_categories' => '0',
				),
				'layouts' => array(
					'layout_644bead13f390' => array(
						'key' => 'layout_644bead13f390',
						'name' => 'cards',
						'label' => 'Cards',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_644beb18b5afa',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_644beb4cb5afc',
								'label' => 'Content',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_644beb6ab5afd',
								'label' => 'List',
								'name' => 'list',
								'aria-label' => '',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'acfe_repeater_stylised_button' => 0,
								'layout' => 'row',
								'min' => 0,
								'max' => 0,
								'collapsed' => '',
								'button_label' => 'Add Card',
								'rows_per_page' => 20,
								'sub_fields' => array(
									array(
										'key' => 'field_644beb80b5afe',
										'label' => 'Image',
										'name' => 'image',
										'aria-label' => '',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'uploader' => '',
										'return_format' => 'array',
										'acfe_thumbnail' => 0,
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
										'preview_size' => 'medium',
										'library' => 'all',
										'parent_repeater' => 'field_644beb6ab5afd',
									),
									array(
										'key' => 'field_644beb87b5aff',
										'label' => 'Title',
										'name' => 'title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'parent_repeater' => 'field_644beb6ab5afd',
									),
									array(
										'key' => 'field_644beb98b5b00',
										'label' => 'Subtitle',
										'name' => 'subtitle',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'parent_repeater' => 'field_644beb6ab5afd',
									),
									array(
										'key' => 'field_644beba9b5b01',
										'label' => 'Description',
										'name' => 'description',
										'aria-label' => '',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'acfe_textarea_code' => 0,
										'maxlength' => '',
										'rows' => '',
										'placeholder' => '',
										'new_lines' => '',
										'parent_repeater' => 'field_644beb6ab5afd',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_644bec71b5b02' => array(
						'key' => 'layout_644bec71b5b02',
						'name' => 'products',
						'label' => 'Products',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_644bec77b5b04',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_644bec7eb5b05',
								'label' => 'Content',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_644fb43e34d84',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => '',
							),
							array(
								'key' => 'field_644bec86b5b06',
								'label' => 'List',
								'name' => 'list',
								'aria-label' => '',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'acfe_repeater_stylised_button' => 0,
								'layout' => 'block',
								'min' => 0,
								'max' => 0,
								'collapsed' => 'field_644fb19d34d7e',
								'button_label' => 'Add Tab',
								'rows_per_page' => 20,
								'sub_fields' => array(
									array(
										'key' => 'field_644fb19d34d7e',
										'label' => 'Category',
										'name' => 'category',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'parent_repeater' => 'field_644bec86b5b06',
									),
									array(
										'key' => 'field_644fb1f234d7f',
										'label' => 'Products',
										'name' => 'products',
										'aria-label' => '',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'acfe_repeater_stylised_button' => 0,
										'layout' => 'block',
										'min' => 0,
										'max' => 0,
										'collapsed' => 'field_644fb21634d81',
										'button_label' => 'Add Product',
										'rows_per_page' => 20,
										'sub_fields' => array(
											array(
												'key' => 'field_644fb20b34d80',
												'label' => 'Image',
												'name' => 'image',
												'aria-label' => '',
												'type' => 'image',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'uploader' => '',
												'return_format' => 'id',
												'acfe_thumbnail' => 0,
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
												'preview_size' => 'medium',
												'library' => 'all',
												'parent_repeater' => 'field_644fb1f234d7f',
											),
											array(
												'key' => 'field_644fb21634d81',
												'label' => 'Title',
												'name' => 'title',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'parent_repeater' => 'field_644fb1f234d7f',
											),
											array(
												'key' => 'field_644fb21c34d82',
												'label' => 'Description',
												'name' => 'description',
												'aria-label' => '',
												'type' => 'textarea',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'acfe_textarea_code' => 0,
												'maxlength' => '',
												'rows' => 3,
												'placeholder' => '',
												'new_lines' => '',
												'parent_repeater' => 'field_644fb1f234d7f',
											),
											array(
												'key' => 'field_644fb22f34d83',
												'label' => 'Link',
												'name' => 'link',
												'aria-label' => '',
												'type' => 'link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'return_format' => 'array',
												'parent_repeater' => 'field_644fb1f234d7f',
											),
										),
										'parent_repeater' => 'field_644bec86b5b06',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_644fb4c656a00' => array(
						'key' => 'layout_644fb4c656a00',
						'name' => 'tools',
						'label' => 'Tools',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_644fb4c656a01',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_644fb4c656a02',
								'label' => 'Content',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_644fb4c656a03',
								'label' => 'Link',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'return_format' => 'array',
							),
							array(
								'key' => 'field_644fb4c656a04',
								'label' => 'List',
								'name' => 'list',
								'aria-label' => '',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'acfe_repeater_stylised_button' => 0,
								'layout' => 'block',
								'min' => 0,
								'max' => 0,
								'collapsed' => 'field_644fb4c656a05',
								'button_label' => 'Add Tab',
								'rows_per_page' => 20,
								'sub_fields' => array(
									array(
										'key' => 'field_644fb4c656a05',
										'label' => 'Category',
										'name' => 'category',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'parent_repeater' => 'field_644fb4c656a04',
									),
									array(
										'key' => 'field_644fb4c656a06',
										'label' => 'Tools',
										'name' => 'products',
										'aria-label' => '',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_save_meta' => 0,
										'acfe_repeater_stylised_button' => 0,
										'layout' => 'block',
										'min' => 0,
										'max' => 0,
										'collapsed' => '',
										'button_label' => 'Add Tool',
										'rows_per_page' => 20,
										'sub_fields' => array(
											array(
												'key' => 'field_644fb4c656a07',
												'label' => 'Image',
												'name' => 'image',
												'aria-label' => '',
												'type' => 'image',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'uploader' => '',
												'return_format' => 'id',
												'library' => 'all',
												'acfe_thumbnail' => 0,
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
												'preview_size' => 'medium',
												'parent_repeater' => 'field_644fb4c656a06',
											),
											array(
												'key' => 'field_644fb4c656a08',
												'label' => 'Title',
												'name' => 'title',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'parent_repeater' => 'field_644fb4c656a06',
											),
											array(
												'key' => 'field_644fb4c656a09',
												'label' => 'Description',
												'name' => 'description',
												'aria-label' => '',
												'type' => 'textarea',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'acfe_textarea_code' => 0,
												'maxlength' => '',
												'rows' => 3,
												'placeholder' => '',
												'new_lines' => '',
												'parent_repeater' => 'field_644fb4c656a06',
											),
											array(
												'key' => 'field_644fb4c656a0a',
												'label' => 'Link',
												'name' => 'link',
												'aria-label' => '',
												'type' => 'link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'return_format' => 'array',
												'parent_repeater' => 'field_644fb4c656a06',
											),
										),
										'parent_repeater' => 'field_644fb4c656a04',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_6450135644e3a' => array(
						'key' => 'layout_6450135644e3a',
						'name' => 'cases',
						'label' => 'Cases',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6450136844e46',
								'label' => 'Cases',
								'name' => 'cases',
								'aria-label' => '',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'clone' => array(
									0 => 'field_645012c6d0c12',
									1 => 'field_645012c6d0c13',
									2 => 'field_645012c6d0c14',
									3 => 'field_645012c6d0c15',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
								'acfe_seamless_style' => 0,
								'acfe_clone_modal' => 0,
								'acfe_clone_modal_close' => 0,
								'acfe_clone_modal_button' => '',
								'acfe_clone_modal_size' => 'large',
							),
						),
						'min' => '',
						'max' => '1',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
					'layout_644fc05ea8a72' => array(
						'key' => 'layout_644fc05ea8a72',
						'name' => 'resources',
						'label' => 'Resources',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_64502901ef3d3',
								'label' => 'Resources',
								'name' => 'resources',
								'aria-label' => '',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 0,
								'clone' => array(
									0 => 'field_6450283ce2e37',
									1 => 'field_64502842e2e38',
									2 => 'field_6450286fe2e3a',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
								'acfe_seamless_style' => 0,
								'acfe_clone_modal' => 0,
								'acfe_clone_modal_close' => 0,
								'acfe_clone_modal_button' => '',
								'acfe_clone_modal_size' => 'large',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
				),
				'min' => '',
				'max' => '',
				'button_label' => 'Add Section',
				'acfe_flexible_layouts_previews' => false,
			),
			array(
				'key' => 'field_644fc16c8680a',
				'label' => 'Demo',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_644ff06eb73ac',
				'label' => 'Demo',
				'name' => 'demo',
				'aria-label' => '',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_save_meta' => 0,
				'clone' => array(
					0 => 'field_644fc17a8680b',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
				'acfe_seamless_style' => 0,
				'acfe_clone_modal' => 0,
				'acfe_clone_modal_close' => 0,
				'acfe_clone_modal_button' => '',
				'acfe_clone_modal_size' => 'large',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-home.blade.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	));

endif;